### ISSUE TITLE
Missing video on https://docs.flutterflow.io/resources/backend-logic/rest-api/

### ISSUE THREAD

**Issue by 1stthingapps** [FlutterFlow/flutterflow-documentation#103]
### Documentation Feedback

Thank you for helping us review the new docs! Please fill out the following template to provide 
your feedback.

---

#### Page URL [REQUIRED]

Please provide the URL of the documentation page or the complete URL of the section heading you are 
reviewing:

`URL of the doc page/section head` 

#### Feedback Type [REQUIRED]

Please select the type of feedback:
- [x] Typo/Error
- [ ] Incorrect Information
- [ ] Improvement Suggestion
- [ ] Usability Issue
- [ ] Structure Feedback
- [ ] Other (please specify):

#### Detailed Description [REQUIRED]

Please provide a detailed description of the feedback:

- **Issue Description:**
    - What is the issue or suggestion?

- **Suggested Fix or Improvement:**
    - What would you suggest to fix or improve this issue?

#### Screenshots (if applicable)

If the feedback is related to visual elements or specific sections, please provide screenshots:

#### Additional Context

Please provide any additional context or information that might help us understand your feedback better:

---

Thank you for your valuable feedback! We appreciate your help in improving our documentation.

**Comment by 1stthingapps** [comment]
Hi Pooja-

Theres a missing video in the section on setting up APIs. https://docs.flutterflow.io/resources/backend-logic/rest-api/#passing-request-headers

**Comment by PoojaB26** [comment]
@1stthingapps where is the missing video? Can you show a screenshot, because I do see a video in the section you referred.

**Comment by 1stthingapps** [comment]
Ah- weird - it shows now. It didn't before (and I did refresh the page a few times). Other videos showed no prob. :)

**Comment by 1stthingapps** [comment]
AH no- its still missing
![image](https://github.com/user-attachments/assets/e48a92ce-8825-4dd6-bebc-1f561082096b)

**Comment by PoojaB26** [comment]
Ah I see, we'll look into it, thanks!!

**Comment by pinkeshmars** [comment]
@pooja for me, it did appear after a page refresh. But we need to keep an eye on such instances. If it happens in a large amount we may need to get in contact with the Arcade team.
