### ISSUE TITLE
how to resolve this error background service issue in the Android 14 version Flutter Flow

### ISSUE THREAD

**Issue by roshansrashtasoft** [FlutterFlow/flutterflow-documentation#111]
I/ImeTracker(27343): com.flutterflow.eas*****:ebc888e6: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
I/InputMethodManager_LC(27343): hsifw() - flag : 0
I/InputMethodManager_LC(27343): hsifw() - mService.hideSoftInput
D/AndroidRuntime(27343): Shutting down VM
E/AndroidRuntime(27343): FATAL EXCEPTION: main
E/AndroidRuntime(27343): Process: com.flutterflow.eas*****, PID: 27343
E/AndroidRuntime(27343): java.lang.RuntimeException: Unable to create service id.flutter.flutter_background_service.BackgroundService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{bb79130 27343:com.flutterflow.eas*****/u0a891} targetSDK=34
E/AndroidRuntime(27343): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
E/AndroidRuntime(27343): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime(27343): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
E/AndroidRuntime(27343): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27343): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime(27343): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime(27343): 	at android.app.ActivityThread.main(ActivityThread.java:8919)
E/AndroidRuntime(27343): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27343): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
E/AndroidRuntime(27343): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/AndroidRuntime(27343): Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{bb79130 27343:com.flutterflow.eas*****/u0a891} targetSDK=34
E/AndroidRuntime(27343): 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
E/AndroidRuntime(27343): 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
E/AndroidRuntime(27343): 	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
E/AndroidRuntime(27343): 	at android.os.Parcel.readParcelable(Parcel.java:4864)
E/AndroidRuntime(27343): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
E/AndroidRuntime(27343): 	at android.os.Parcel.createException(Parcel.java:3053)
E/AndroidRuntime(27343): 	at android.os.Parcel.readException(Parcel.java:3036)
E/AndroidRuntime(27343): 	at android.os.Parcel.readException(Parcel.java:2978)
E/AndroidRuntime(27343): 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7234)
E/AndroidRuntime(27343): 	at android.app.Service.startForeground(Service.java:862)
E/AndroidRuntime(27343): 	at androidx.core.app.ServiceCompat$Api34Impl.startForeground(ServiceCompat.java:239)
E/AndroidRuntime(27343): 	at androidx.core.app.ServiceCompat.startForeground(ServiceCompat.java:172)
E/AndroidRuntime(27343): 	at id.flutter.flutter_background_service.BackgroundService.updateNotificationInfo(BackgroundService.java:175)
E/AndroidRuntime(27343): 	at id.flutter.flutter_background_service.BackgroundService.onCreate(BackgroundService.java:107)
E/AndroidRuntime(27343): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
E/AndroidRuntime(27343): 	... 9 more
I/Process (27343): Sending signal. PID: 27343 SIG: 9
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"70","method":"getStack","params":{"isolateId":"isolates/7478120073204235"}}
Failed to send request: {"jsonrpc":"2.0","id":"69","method":"getMemoryUsage","params":{"isolateId":"isolates/7478120073204235"}}
Failed to send request: {"jsonrpc":"2.0","id":"71","method":"getObject","params":{"isolateId":"isolates/7478120073204235","objectId":"classes/7822"}}
Failed to send request: {"jsonrpc":"2.0","id":"72","method":"invoke","params":{"isolateId":"isolates/7478120073204235","targetId":"objects/98","selector":"toString","argumentIds":[],"disableBreakpoints":true}}

And How To Add this Permission In the AndroidMainst.xml File in Flutter Flow 

```
<service
            android:name="id.flutter.flutter_background_service.BackgroundService"
            android:foregroundServiceType="location"
        />
```

**Comment by PoojaB26** [comment]
Hi @roshansrashtasoft this doesnt seem to be related to the docs. If this is a bug in the platform, please create an issue in https://github.com/FlutterFlow/flutterflow-issues, but it seems to me, that it is a troubleshooting question, you may want to ask your question in the [community forum. ](https://community.flutterflow.io/ask-the-community)
