### ISSUE TITLE
Broken Documentation Reference from FlutterFlow platform

### ISSUE THREAD

**Issue by Rodriq** [FlutterFlow/flutterflow-documentation#119]
Getting to the docs from places around the platform where specific documentation is mentioned is broken.

## Expected behavior
Take me to the docs needed

## Actual behavior
Takes me to Page Not Found

## Examples
See some places where the docs are mentioned under 

- **Settings and Integrations** > **Firebase**
  - https://docs.flutterflow.io/firebase-setup
  - https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/storage-rules

- **Settings and Integrations** > **Mobile Deployment**

_It can be helpful to add a global redirect to handle unknown cases._

**Comment by PoojaB26** [comment]
We do have a redirects setup to handle most of the redirects. But these URL structures are old and don't belong to the latest gitbook hierarchy structure as well. (probably was erroring out before as well or gitbook might have added their own redirects when we changed the hierarchy, but we dont have that list) But any other URL that was part of the latest gitbook hierarchy do have redirects. 

And about this ticket, I do have a PR already submitted to fix the above URLs from the product, waiting for it to be merged!
