### ISSUE TITLE
Flutterflow Community Account Name Update

### ISSUE THREAD

**Issue by ZapeeoSheikh** [FlutterFlow/flutterflow-documentation#189]
### Documentation Feedback

Thank you for helping us review the new docs! Please fill out the following template to provide 
your feedback.

---

#### Page URL [REQUIRED]

Please provide the URL of the documentation page or the complete URL of the section heading you are 
reviewing:

`URL of the doc page/section head` 

#### Feedback Type [REQUIRED]

Please select the type of feedback:
- [ ] Typo/Error
- [ ] Incorrect Information
- [ ] Improvement Suggestion
- [1] Usability Issue
- [ ] Structure Feedback
- [ ] Other (please specify):

#### Detailed Description [REQUIRED]

Please provide a detailed description of the feedback:

- **Issue Description:**
    - What is the issue or suggestion?
When you login the flutterflow community using flutterflow then It will update you profile name every time based on your Google account. No matter if you have changed your name on flutterflow community portal or not.

- **Suggested Fix or Improvement:**
    - What would you suggest to fix or improve this issue?
When the flutterflow account name has been updated so don't update the name if we are doing google authentication.
#### Screenshots (if applicable)

If the feedback is related to visual elements or specific sections, please provide screenshots:
<img width="1377" alt="asdsadadasdasd" src="https://github.com/user-attachments/assets/df7bec3e-ea47-4d13-889f-a91dfe69682e">

#### Additional Context

Please provide any additional context or information that might help us understand your feedback better:

---

Thank you for your valuable feedback! We appreciate your help in improving our documentation.

**Comment by PoojaB26** [comment]
Hi @ZapeeoSheikh, unfortunately this is not a documentation request so we will have to close this. 

However to answer your question, the name will be updated only when you tap on the Community tab from FlutterFlow and it will take the name that is available in your FlutterFlow platform profile. So if you want to change it for once, change it in your profile in FF and then the same name will be used in the community.
