### ISSUE TITLE
Backend Query No Usage Example

### ISSUE THREAD

**Issue by AdrKacz** [FlutterFlow/flutterflow-documentation#213]
### Documentation Feedback

Thank you for helping us review the new docs! Please fill out the following template to provide 
your feedback.

---

#### Page URL [REQUIRED]

Please provide the URL of the documentation page or the complete URL of the section heading you are 
reviewing:

`https://docs.flutterflow.io/resources/backend-query` 

#### Feedback Type [REQUIRED]

Please select the type of feedback:
- [ ] Typo/Error
- [ ] Incorrect Information
- [x] Improvement Suggestion
- [ ] Usability Issue
- [ ] Structure Feedback
- [ ] Other (please specify):

#### Detailed Description [REQUIRED]

Please provide a detailed description of the feedback:

- **Issue Description:**
    - What is the issue or suggestion? The backend query gives clear details on what it is and how to benefits from cache but doesn't show how to use the results in the page or components.

- **Suggested Fix or Improvement:**
    - What would you suggest to fix or improve this issue? I'd suggest adding a section that explain how to use the results in different part of the page (page's triggers and widget's triggers)

#### Screenshots (if applicable)

If the feedback is related to visual elements or specific sections, please provide screenshots: Not applicable

#### Additional Context

Please provide any additional context or information that might help us understand your feedback better: Not applicable

---

Thank you for your valuable feedback! We appreciate your help in improving our documentation.

**Comment by AdrKacz** [comment]
My bad, just realized you added example on how to use with Widgets here: https://docs.flutterflow.io/resources/backend-query/query-collection#using-query-data

However, I don't find documentation about how to use the results in page's triggers (e.g. access results on phone shake or access results after they load/update to perform actions)

**Comment by pinkeshmars** [comment]
> However, I don't find documentation about how to use the results in page's triggers (e.g. access results on phone shake or access results after they load/update to perform actions)

Hi @AdrKacz You can use these docs to trigger a query and use its results in page's trigger: [Firestore](https://docs.flutterflow.io/integrations/database/cloud-firestore/firestore-actions/#query-collection-action) or [Supabase](https://docs.flutterflow.io/integrations/database/supabase/database-actions#query-rows-action).

Let us know if we should close this ticket. Thanks!

**Comment by AdrKacz** [comment]
@pinkeshmars Yes thank you, this is working fine 👍
