### ISSUE TITLE
VSCode extension API key

### ISSUE THREAD

**Issue by rantoniuk** [FlutterFlow/flutterflow-documentation#232]
https://docs.flutterflow.io/concepts/custom-code/vscode-extension/#add-api-keys

The VSCode extension requires an API Key. However, when I go to my account page, there is no API token box to generate the API key. This whole API Token box is missing at the bottom of the page.

**Comment by pinkeshmars** [comment]
Hi @rantoniuk, you don't need to generate it. If you scroll down a bit, you'll find a box labeled 'API Token' where you can copy the API token directly.

https://github.com/user-attachments/assets/184d8c70-756a-4412-bbae-43703dacd300

**Comment by rantoniuk** [comment]
"I would if I could, but I don't so I won't" :D 
<img width="1261" alt="Screenshot 2024-12-19 at 13 51 29" src="https://github.com/user-attachments/assets/2c72dda6-10ac-463a-8614-780749537a8d" />

As explained above, this section is not present on my profile.

**Comment by pinkeshmars** [comment]
Oh, it seems that you are currently on the free plan. Unfortunately, the VS Code extension requires downloading code, which is only available with a [paid plan](https://www.flutterflow.io/pricing).
